# Generated by Django 4.1.3 on 2022-11-30 19:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_login', models.CharField(max_length=50)),
                ('user_password', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(6)])),
            ],
        ),
    ]
